massenergize/api

- .github/workflows/django.yml
- .gitignore
- src/_main_/settings.py
- src/api/handlers/page_settings__home.py
- src/api/store/graph.py
- src/api/store/page_settings__home.py
- src/api/store/team.py
- src/api/urls.py
- src/api/views.py
- src/database/models.py
The API includes carbon_footprint_reduction target and attained values the same as it does households and actions completed.  This allows the community portal to show carbon_footprint_reduction graphs (enabled by a community admin by setting target > 0). Also include the attained carbon_footprint_reduction for teams.
Addresses API#110 and Frontend-portal#186
> Enable carbon-reduction targets and attained values

- src/api/store/action.py
Fixes a bug introduced where deleted actions where showing up where they shouldn't have.
> Deleted actions shouldn't show in list by default

- src/api/handlers/team.py
- src/api/services/team.py
- src/api/store/team.py
For the teams redesign, we want to display the preferred names of the users who are on a given team. This endpoint allows us to access that information without exposing any sensitive data of a user.
> New members preferred names endpoint

- src/api/handlers/userprofile.py
- src/api/services/userprofile.py
Update user endpoint is returning server_error all the time.
Error:
This PR fixes that.
> fix update user

- src/api/store/action.py
- src/api/store/event.py
- src/api/store/team.py
- src/api/store/testimonial.py
On updating Actions, Testimonials, Events, etc, enable clearing the link to primary community, logo, etc
This goes along with the Admin Portal changes to add "--" to dropdowns
> Handle Update cases where community set to "no community" etc

- src/api/store/community.py
- src/database/models.py
- src/requirements.txt
#317 is passing back date with messages, so admin portal can show them
#318 is for donut graph statistics, so initial and/or attained values can be selected for inclusion by cadmin
> Issues 317 and 318

- src/api/services/userprofile.py
Fixes an issue where some email addresses (with dots or +) were rejected by the regex test.  Reported by Megan Sullivan who couldn't import some users.
> Issue 377 - regex checking of e-mail addresses

- src/api/store/download.py
- src/api/tests/test_download.py
This change improves performance of `_get_user_teams_cells`
by replacing a loop that ran multiple database queries. The
new code builds and runs a single query to fetch all the
team names associated with a given user.
Also:
- Improved `test_download.py` to validate team names
- Minor whitespace cleanup
Testing
=======
local runsever
--------------
Ran curl http://localhost:8000/api/downloads.users before and
after change.
Using sample database, download time went from 2+ minutes to
under 12 seconds.
It it likely we can make additional improvements to other
database queries performed by the user download code.
unit tests
----------
```
% ./manage.py test api.tests.test_download.DownloadTestCase
Creating test database for alias 'default'...
Initializing 0 Carbon Calc defaults from db
System …
```
> download.users: optimize _get_user_teams_cells

- src/api/handlers/misc.py
- src/api/services/misc.py
- src/api/store/misc.py
- src/database/raw_data/portal/menu.json
New route `api/menus.remake` 
This route uses the content of `menu.json` we have to fill the "menus" table in the database. 
In this PR, I have made changes to the `menu.json` and assigned ids to the menu items.  
These ids  help target the navigation menu when we are testing various functionality via the nav menu. 
Just hit the `api/menus.remake` in dev/canary/prod/ or any mode (on backend) to inflate the menus table with the new data.
_Nothing will change for the frontend_
In future, when we are ready to make more changes to the structure of the menu, we just need to edit the `menu.json` and hit the `api/menus.remake` route to update. 
**DISCLAIMER** 
@BradHN1 , the intended changes happened inside the `menu.json` `misc.py` in (handler, services, store) the rest are just formatting …
> New menu remake route, and changes to menu

- src/api/handlers/community.py
- src/api/handlers/userprofile.py
- src/api/services/userprofile.py
- src/api/store/download.py
- src/api/store/userprofile.py
- src/api/tests/test_communities.py
- src/api/tests/test_download.py
- src/api/tests/test_userprofile.py
- src/database/models.py
FIxes 2 issues and adds a new piece of functionality for use at public events this weekend
479 - only send a "Welcome" e-mail the first time a profile is validated (which means, when accepts_terms_and_conditions goes from false to true)
486 - Users listForCommunityAdmin and download from admin now includes Guest users as well as standard users;
488 - add a route users.listForPublicView which passes back users from a community with points above a certain value.  
479 - this fixes a bug where certain users received more than one e-mail, every time users.create was called - which could happen multiple times.
486 - We needed a way for admins to see Guest users and be able to contact them.  For example:
488 - sample output from the new route users.listForPublicView:
The purpose is to be able …
> API Issues 479, 486, 488

- src/api/handlers/action.py
- src/api/store/action.py
- src/database/models.py
Related Ticket :  https://github.com/massenergize/api/issues/542
https://user-images.githubusercontent.com/26961591/180138783-510d3392-0e66-4423-a21f-f6bf7127e371.mov
> tags in actions will get copied over, and tweaks to action serializer

- src/api/store/community.py
Related to ticket #553  
This change will now make primary contact an admin of the community, as described in the ticket. 
- User is already added  into communityAdminGroup already, so we just had to flip the is_admin property
closes #553
> tiny tweak to allow primary contact to be admin automatically

- src/api/handlers/download.py
- src/api/handlers/misc.py
- src/api/services/download.py
- src/api/store/community.py
- src/api/store/event.py
- src/database/utils/settings/admin_settings.py
- src/database/utils/settings/user_settings.py
NB: Automated tests will fail, cos the old tests dont cater for the new changes yet! ( Will be done soon)
> Continue brads preference changes

- src/api/store/action.py
- src/api/store/event.py
- src/api/store/vendor.py
Back out the is_approved logic until we have user submitted actions, events, vendors.
> 613 - bug fix for making actions/vendors/events live if not pre-approved

- src/api/store/userprofile.py
A missing logo file caused the invite users to fail.
Added protection so it didn't crash
> 642 - protection against missing logo file

- src/_main_/utils/common.py
- src/_main_/utils/footage/FootageConstants.py
- src/_main_/utils/footage/spy.py
- src/api/handlers/action.py
- src/api/handlers/community.py
- src/api/handlers/summary.py
- src/api/services/action.py
- src/api/services/auth.py
- src/api/services/community.py
- src/api/services/summary.py
- src/api/store/action.py
- src/api/store/summary.py
- src/api/tests/common.py
- src/api/tests/test_user_engagements.py
- src/database/models.py
- src/database/utils/common.py
> Show admins what todo 2

- src/api/store/userprofile.py
Users who are members  of multiple communities will not be deleted by a Cadmin
> Change: Prevent Cadmin from Deleting users with multiple communities

- src/_main_/utils/constants.py
- src/_main_/utils/emailer/send_email.py
- src/api/services/admin.py
- src/api/services/message.py
- src/api/services/webhook.py
- src/api/store/message.py
This PR fixes the issue where the footage actor is null when admins reply to user messages from their email app. The issue occurs because the user_id and user_email fields in the API's context object are null since the user is not logged in. To solve the problem, we pass and use the sender email from the reply to get the associated user and use that user as the actor for the footage. This approach solves the bug by properly associating the actor with the footage, even when the user is not logged in.
> Bug Fix: Postmark footage Error

- src/api/services/page_settings__home.py
- src/api/store/page_settings__home.py
Here, I am just sending out the full Json for homepage_settings.update response. Cos on the frontend, that full json, is needed to replace the cached version in redux after update
> full json return when homepage settings is updated

- src/socket_notifications/consumers/user_session_tracker_consumer.py
So this error was kind of showing up every time the socket disconnected. 
`...channels/routing.py:71> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fefdbd501f0>()]>> for connection <WebSocketProtocol client=['172.31.28.234', 29590] path=b'/ws/me-client/connect/'> took too long to shut down and was killed.`
I was able to trace it down to the async.sleep we were using. We were not cleaning up appropriately during disconnects. So in this PR, all async counts are being cleaned up on disconnects. So that warning should not be appearing anymore.
I changed the thing loop  wait time from 5 seconds to 10 minutes. I mean we are not doing that much in that function for the 50-second-checks to amount to anything in compute power. But, in future when we have like 4million users, it …
> warning wont show in console anymore

- src/api/store/community.py
- src/task_queue/events_nudge/user_event_nudge.py
Fix so admin lists of communities are sorted rather than a random order.
> Sort communities by name on list routes

- src/database/models.py
- src/task_queue/views.py
A crash in user_is_due_for_mou caused a problem signing in for Cadmins, once they had been sent a notification.
> Error on cadmin sign-in: user_due_for_mou exception

- src/api/handlers/userprofile.py
- src/api/store/action.py
- src/api/store/event.py
- src/api/store/testimonial.py
- src/api/store/vendor.py
Fix two bugs which came in with the security API
719 - updating user profile, if user_id specfied
720 - copying events actions or testimonials and saving them
> API Bugs  719 and 720

- src/api/store/action.py
- src/api/store/admin.py
- src/api/store/community.py
- src/api/store/download.py
- src/api/store/event.py
- src/api/store/message.py
- src/api/store/page_settings.py
- src/api/store/policy.py
- src/api/store/team.py
- src/api/store/testimonial.py
- src/api/store/userprofile.py
- src/api/utils/api_utils.py
This PR addresses issue 727 (Community Admins who are also Super Admins should have admin access to any community.
> Fix route permissions so superadmins always have access

- src/_main_/utils/footage/spy.py
https://github.com/massenergize/api/assets/42780120/549f2cdc-33a8-442a-897a-63279d3301fa
> Cadmin activities will now exclude sadmin footages

- src/api/handlers/event.py
- src/api/services/event.py
- src/api/store/action.py
- src/api/store/event.py
- src/api/tests/test_actions.py
- src/api/tests/test_events.py
closes #730 
- Added `/events.share` route for event sharing instead of `/events.update` which was causing issues for unauthorised users.
- Fixed broken tests
- Added unit tests for the new route
> New Route for Event Sharing

- src/api/store/testimonial.py
https://github.com/massenergize/api/assets/26961591/1d3df220-70a8-440f-a6b2-4d22a8128f80
> users will now be able to submit testimonials

- src/api/handlers/userprofile.py
- src/api/store/userprofile.py
- src/requirements.txt
Just modified Mattea's username validation code a bit.
> Filter bad words from username

- src/api/store/media_library.py
The` .set` method of the M2M relationship accepts a list of `ids,` but we were passing a list of objects.  This Pr fixes this issue by replacing the list of objects with the list of ids
> media lib footage resolved

- src/task_queue/events_nudge/cadmin_events_nudge.py
- src/task_queue/events_nudge/user_event_nudge.py
> Events nudge

- src/api/handlers/community.py
- src/api/store/community.py
- src/api/tests/test_communities.py
Added extra field  `distance` to `community.location` when `zipcode` argument is provided to `communities.list` to display the distance between given zipcode and community's zipcode. An optional `max_distance` with a default value of 25 miles will filter communities with a distance less than or equal to that value.
> Add arguments to communities.list for geographic range.

- src/api/services/auth.py
> Email-Password Signup Email Verification Now Uses Postmark

- src/task_queue/events_nudge/cadmin_events_nudge.py
One line fix to prevent duplicate events and properly exclude events from your community or ones you've already shared.
> 779 - cadmin nudge issue

- src/api/utils/filter_functions.py
> Search and Filter by Community Fixed

- src/api/store/action.py
- src/api/store/event.py
- src/api/store/vendor.py
- src/api/tests/test_mou_reminder.py
- src/api/tests/test_teams.py
- src/carbon_calculator/carbonCalculator.py
- src/carbon_calculator/queries.py
Fixes several bugs encountered in testing
Three bugs in API for undefined variable user_media_upload
Two CC bugs: one fixing unitialized variables in CalculatorAction model, another for new CC Actions without associated Questions.
Unit tests pass.
Calculator actions titles not missing in Edit Action in Admin portal
> Carbon Calculator bug fixes, and bugs uncovered by unit tests

- src/task_queue/nudges/user_event_nudge.py
Some deleted users have received nudges, because they hadn't been marked as deleted in CommunityMembers
Explicitly require is_deleted=False for users to get nudged
Resolves issue #841
> 841 - prevent deleted users from getting nudged

- src/task_queue/nudges/cadmin_events_nudge.py
This PR is to fix the bug #874 in production.
As described in the ticket, the event sharing nudge to cadmins has been failing for the last several weeks, since changes were made relating to the user sign on method (in user_info).
Testing should have caught this bug but it didn't.
This PR is to master, so the bug fix can be deployed this weekend before the nudge goes out on Monday.
We will see on Monday that the Cadmin Event sharing nudge goes out and the Task completes
> Fix for critical bug API 874 - cadmin events nudge fails

- src/api/store/userprofile.py
This pull request addresses a key functionality update in the user management feature of our project.
- **Enhanced Deletion Permissions for Super Administrators**: A change has been made in the can_be_deleted function found in the userprofile API to enable super administrators to delete user profiles of non-super administrators. This provides super administrators with better control and ability to manage users in the application.
closes https://github.com/massenergize/frontend-admin/issues/1124
> Fix: Allow Super Admins to Delete Non-Super Admin Profile

- src/api/store/event.py
- src/database/models.py
This pull request includes a new function in the database model to get the list of communities an event is shared with. Community admins can set notification settings for communities an event is shared with when they apply the settings to all communities.
> Feature: Add 'Shared-To' Communities to Event Notification Settings

- src/Makefile
- src/_main_/settings.py
This update implements a refined deployment strategy in the Makefile, that includes the tagging and deploying of production, canary, and dev versions. It also introduces separate, environment-specific migration commands for robust environment management. Complementary alterations have been made in settings.py to correctly identify the associated environments.
> Chore: Refine build and deployment strategy in Makefile and settings.py

- src/_main_/utils/feature_flags/FeatureFlagConstants.py
- src/api/store/community.py
Added functions in FeatureFlagConstants.py for handling "all_except" audience type. Extended check_community_membership() in community.py to modify the community membership of a feature flag based on the current audience setting and the should_enable parameter. This further refines the management of feature flag audience configurations.
> fix: Add feature flag audience checks and modifications

- src/api/store/download.py
This pull request updates the column headers for the "_campaign_interaction_performance_download" method. Previously, the column headers were labeled as "Campaign" and "Action", but these have been updated to "Source" and "Element". A new column, "Element", has been added to provide information about the button type of the interaction
> :recycle: Update column headers in campaign interaction download 

- src/api/store/event.py
This pull request addresses and resolves a bug that was causing the events list on the community portal to be truncated. The root cause of this issue was a faulty query that attempted to retrieve events for a community using a null community_id. The solution implemented corrects this by utilizing the community's subdomain for event retrieval instead of the community_id.
> Fix: Display Full Event List on Community Portal

- src/api/store/page_settings__home.py
- src/database/models.py
Fixes Edit xxx Page Settings titles on Admin portal.
This PR addresses issue #948 
A bug I introduced last week caused a cosmetic issue the Admin Portal pages to edit PageSetting.
Add back in the community summary info with the page_settings response
I've tested it locally with the admin portal by editing each page settings.  This is done from the Community Profile page, choosing the Pages tab, and selecting each of the pages to edit.
> 948 - return community summary info with PageSettings

- src/database/models.py
This PR duplicates #948 which will fix the missing logos (issue #954):
1. Logos are missing from community sites
2. Events on events page all listed as "SHARED"
These bugs would also be fixed by merging dev -> canary -> prod, but if the testing for this woudl take a couple extra days you can merge and deploy this PR.
Tahiru's PR 952 to fix Events is probably not required, as the bug he was fixing is gone with this PR
No migrations are required.
Check that the community site logos come back when this is deployed
Check that the Events are not all listed as SHARED, but only the ones shared from other communities.
> Prod fix for community logo and events missing

- src/api/handlers/community.py
- src/database/models.py
This pull request addresses the recent changes made to the endpoint for fetching feature flags for communities. Previously, the endpoint was modified to fetch feature flags directly, but this has been rolled back to the original implementation where feature flags are accessed from the community object.
> Hotfix: Rollback of Feature Flags Fetching Endpoint

- src/task_queue/nudges/user_event_nudge.py
This PR addresses the issue of missing EventNudgeSetting instances when sending nudges. Previously, if an EventNudgeSetting did not exist for a particular event, the system would fail to send a nudge for that event. This fix ensures that a new EventNudgeSetting is created with default settings if one does not already exist, allowing the nudge to be sent as expected.
> Fix: create new  EventNudgeSetting if doent exist when sending Nudges

- src/task_queue/nudges/cadmin_events_nudge.py
Fixes an exception in the Cadmin weekly event sharing nudge due to a variable being renamed.
Please test this and get it into canary and prod ASAP.  Thanks
> 966 - fix Cadmin Event Sharing nudge

- src/api/handlers/misc.py
- src/api/services/misc.py
- src/api/store/misc.py
- src/api/utils/api_utils.py
Various functions and routes have been introduced to facilitate the loading of menu items. This includes the helper functions in the api_utils file to filter and prepare the menu items, as well as appropriate routes and handlers for these items. These additions will allow easier interaction with the menus within a given community context.
> Added functionality to load menu items

- src/Makefile
- src/_main_/settings.py
- src/_main_/utils/route_handler/__init__.py
- src/task_queue/tasks.py
This pull request tries to fix celery tasks executing on multiple instances by using django cache as a locking mechanism.
> Fix Celery task executing in multiple instances

- src/api/store/campaign.py
This pull request introduces a check in the campaign API to verify if a 'community_id' is provided during campaign subscription.
https://github.com/massenergize/api/assets/42780120/4975ad19-0497-4827-8215-68ce77bd5665
> Fix: Addition of Check for Community Selection in Campaign Subscription

- src/api/store/message.py
- src/api/tasks.py
- src/docker-compose.yml
This pull request introduces a locking mechanism to tasks that run our bulk messaging and feature reactivate feature. This will prevent our tasks from executing multiple times when we have multiple instances running.
> Fix: Add task locking to isolated celery tasks

- src/api/handlers/misc.py
- src/api/services/misc.py
- src/website/views.py
We were getting erros lilke:
```
[request_id=61ab6ec1-b3f3-46a8-a9ad-71cb8b806b80] 2024-05-31 12:19:23,290 ERROR django.request Internal Server Error: /health_check
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
response = get_response(request)
File "/usr/local/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
return callback(request, *args, **kwargs)
File "/src/_main_/utils/metrics/__init__.py", line 21, in wrap
return func(*args, **kwargs)
File "/src/api/handlers/misc.py", …
```
> fix /health_check, /version and /home bug

- src/_main_/utils/constants.py
- src/api/utils/api_utils.py
This PR fixes the removal of subdomain from the menu link structure when the community doesn't have a custom website.
> hotfix 🔥 : community menu like breakage

- src/api/services/webhook.py
- src/api/store/message.py
This pull request fixes the 500 error we encountered on Postmark during inbound message processing. The error was caused by an inconsistent format of the link in the email body used to extract the message ID.
> Fix: inbound message Id extraction

- src/api/tests/test_campaigns.py
- src/api/tests/test_message.py
- src/api/tests/test_technology.py
The setupCC method has been removed from the test_message, test_campaigns, and test_technology files. This change simplifies the setup process of each test by only utilizing the necessary methods from the common module, resulting in a cleaner and more efficient code.
> Remove setupCC method from test files

- src/_main_/settings.py
- src/_main_/utils/stage/__init__.py
This Pull Request addresses the issue where login attempts into the Django Admin site from Dev and Canary environments were aborting due to a CSRF verification failure.
The problem was fixed by adding the CSRF_TRUSTED_ORIGINS setting in the main Django's setting file. The values for ALLOWED_HOSTS are used to set this new setting, ensuring all domains in ALLOWED_HOSTS are recognized as trusted origins for CSRF protection.
> fix: Fix for "CSRF verification failed. Request aborted." issue in Django Admin login on Dev and Canary.

- src/api/utils/api_utils.py
- src/database/raw_data/portal/menu.json
This Pull Request addresses a specific issue where child menu items were being displayed even when their parent menu item was disabled. The changes introduced in this PR ensure that child menu items adhere to the visibility status of their parent menu item. After merging this PR, child menu items will only be displayed if their parent menu item is enabled, enhancing the consistency and usability of our navigation menus.
> Fix: Display Issue of Child Menu Items

- src/api/decorators.py
- src/api/tests/integration/test_custom_menu.py
- src/database/raw_data/portal/menu.json
- src/website/templates/rewiring_america.html
- src/website/urls.py
- src/website/views.py
Made a route that renders the rewiring America page; "Rewiring America" guys have not made provision for React embeds, so it had to be implemented this way. 
So on the frontend, the Iframe just loads the embed through the backend here.
Works with frontend PR : https://github.com/massenergize/frontend-portal/pull/1366
> Feat: Add "Rewiring America" embed

- src/database/raw_data/portal/menu.json
The "Rewiring America" item has been removed from the application's portal menu JSON data. This is because a few things have to be fixed before we can include it to the list of menu items
>  chore: Remove "Rewiring America" item from portal menu data

- src/api/store/community.py
- src/api/tests/common.py
- src/api/tests/integration/test_communities.py
This pull request addresses a critical bug affecting the loading of feature flags into the user portal. With this fix, users wouldn't see features that are not open to their communities.
https://github.com/massenergize/api/assets/42780120/b4b5821a-6c73-42cb-9f61-cf658c1b7557
> Fix: Bug loading all feature flags to the user portal.

- src/_main_/utils/common.py
- src/api/store/common.py
- src/api/store/community.py
- src/api/store/event.py
- src/api/store/message.py
- src/api/store/summary.py
- src/api/store/userprofile.py
- src/api/tasks.py
- src/api/tests/common.py
- src/api/tests/integration/test_communities.py
- src/api/tests/integration/test_events.py
- src/api/tests/integration/test_feature_flags.py
- src/api/tests/integration/test_message.py
- src/api/tests/integration/test_mou_reminder.py
- src/api/tests/unit/utils/test_parse_datetime_to_timezone_aware.py
- src/api/utils/filter_functions.py
- src/carbon_calculator/CCDefaults.py
- src/carbon_calculator/carbonCalculator.py
- src/socket_notifications/consumers/user_session_tracker_consumer.py
- src/task_queue/nudges/cadmin_events_nudge.py
- src/task_queue/nudges/user_event_nudge.py
- src/task_queue/views.py
This pull request addresses two deprecations issues in Django 4:
- The `pytz` package for timezone handling is deprecated in Django 4 and all occurrences of `pytz` have been refactored to use `zoneinfo.ZoneInfo`.
- The `datetime.datetime.utcnow()` function is deprecated and all occurrences of `datetime.datetime.utcnow()` have been replaced with the recommended `datetime.now(timezone.utc)` to ensure timezone-aware datetime objects in UTC.
> Refactor: Timezone Handling to Use ZoneInfo and Replace Deprecated datetime.datetime.utc()

- src/task_queue/nudges/cadmin_events_nudge.py
Minor change to the event sharing email to include the events that are hosted by the community receiving the email
> 1112 - Event sharing email should include our own events

- src/_main_/utils/common.py
- src/api/tests/unit/utils/test_common.py
This pull request fixes a bug in the `is_value` function. The issue was caused by `actions.update` passing `calculator_action` as an argument, which should be an `int`, but was being passed as `null`. Since `is_value` wasn't checking for `null`, the field validator threw an error.
To resolve this, two new value checks `(null and '')` have been added to the `is_value` function. Additionally, the code has been refactored for improved readability.
> Hotfix: Enhance is_value function conditional checks

- src/_main_/utils/common.py
- src/_main_/utils/feature_flag_keys.py
- src/api/constants.py
- src/api/store/misc.py
- src/api/tests/unit/utils/test_common.py
- src/api/utils/api_utils.py
This PR implements a feature that allows hiding menu items under feature flags. With this implementation, the rewiring-america route on the frontend is now controlled by a feature flag.
https://github.com/user-attachments/assets/17a255df-f794-49fd-9c26-653bbd625695
> Hotfix: Hide rewiring America under feature flag

- src/_main_/utils/translation/__init__.py
This pull request enhances the codebase by adding `created_at` and `updated_at` to the `JSON_EXCLUDE_KEYS` list. Additionally, a new regex pattern has been introduced to filter out date and datetime values.
> fix: Add dates to translation exclusion list

- src/_main_/utils/error_messages.py
- src/api/store/supported_language.py
- src/api/tests/common.py
- src/api/tests/integration/test_supported_languages.py
This PR enhances the campaign-supported language lookup functionality by allowing queries using either the campaign ID or the campaign slug. This improvement ensures that the campaign frontend can retrieve the list of supported languages using the campaign slug, which is the available identifier
run `make test`
> ✨ feat: add support for UUID in campaign ID lookup

- src/api/store/testimonial.py
- src/api/tests/common.py
- src/api/tests/unit/utils/test_shareable_testimonial.py
This PR addresses an issue where testimonials were being shared with communities prematurely during their creation process. The function used to fetch communities for auto-sharing was called before assigning the community to the testimonial.
> ✨ Fix Testimonial Auto-Share Sequence During Creation

- src/api/tests/unit/utils/test_filter_functions.py
- src/api/utils/filter_functions.py
This pull request fixes the filter functionality of the users list on the admin portal, which was broken due to the joint query in the get_users_filter_params function. The issue arose from attempting to filter users by both community name and community ID within the same query. This PR resolves the issue by splitting the filters into two separate checks: one for community name and one for community ID.
run `make test`
> Fix: Users List Filter in Admin Portal

- src/_main_/settings.py
- src/api/middlewares/url_resolver_middleware.py
- src/api/tests/unit/utils/test_url_resolver_middleware.py
This pull request introduces significant changes to the `src/api/middlewares/url_resolver_middleware.py` file, focusing on improving URL resolution and handling of host-specific paths. The key changes include the addition of a host map and a new method for resolving paths.
Enhancements to URL resolution:
* Added import for `host_patterns` from `_main_.hosts` and initialized a `host_map` to map host regex patterns to host objects.
* Replaced the direct call to `resolve` with a new method `_resolve_path` that constructs host-specific paths and resolves them.
* Updated the `__call__` method to use `_resolve_path` for resolving request paths and set `request.path_info` accordingly.
New method for path resolution:
* Introduced `_resolve_path` method to handle host-specific path resolution and …
> Fix: Enhance URLResolverMiddleware to support host-based path resolution
