src/database/models.py

fixing json serialization bug

---

src/api/store/community.py
src/api/store/graph.py
src/api/store/misc.py
src/api/store/userprofile.py
src/api/views.py
src/database/models.py

Bug fixes to impact page and community logo

---

src/api/handlers/userprofile.py
src/api/services/userprofile.py
src/api/store/misc.py
src/api/store/team.py
src/api/store/userprofile.py

Added edit household route

---

src/api/handlers/userprofile.py
src/api/store/graph.py
src/api/store/userprofile.py
src/database/models.py

Graphs on home and impact page will be as decided

Fix for Issue #71 - Actions and Households

---

src/api/store/team.py
src/api/views.py

Use TeamMember model consistently

Issue #84 - Teams statistics

---

src/api/handlers/userprofile.py
src/api/services/userprofile.py
src/api/store/utils.py

This fixes a couple errors pointed out by pylint.  You can decide whether the fixes are good.

Bug fixes pointed out by pylint

---

src/_main_/settings.py
src/api/handlers/message.py
src/api/services/message.py
src/api/store/admin.py
src/api/store/community.py
src/api/store/goal.py
src/api/store/graph.py
src/api/store/message.py
src/api/store/misc.py
src/api/store/tag_collection.py
src/api/store/team.py
src/api/store/testimonial.py
src/api/store/utils.py

Removing prints, fixing messages to team admins

Removing prints, fixing messages to team admins

---

.gitignore
src/_main_/settings.py
src/api/handlers/userprofile.py
src/api/store/action.py
src/api/store/userprofile.py

Addresses the following issues:
API#121 - Fix problem with deleted actions causing crashes (Admin#159)
API#122 - Deleting users (Admin

Fix for two issues - deleting users and deleted actions

---

src/api/store/team.py

Fix for Team deletion

---

src/_main_/utils/common.py
src/_main_/utils/massenergize_errors/__init__.py
src/api/handlers/message.py
src/api/handlers/team.py
src/api/handlers/userprofile.py
src/api/handlers/vendor.py
src/api/services/message.py
src/api/services/team.py
src/api/services/userprofile.py
src/api/store/team.py
src/api/store/testimonial.py
src/api/store/userprofile.py
src/api/store/utils.py
src/database/models.py

* Team deletion
* Team Creation (checks admin emails are valid)
* users list fetch sorted by date joined
* Email forwarding to teams

@sam may 2020 sprint 1

---

src/api/handlers/page_settings__home.py

Fixes a bug on Admin portal, unable to change Home Page settings

Fix for Home Page Settings bug : API#140

---

src/api/handlers/vendor.py

Vendor website optional

---

src/api/handlers/graph.py
src/api/services/graph.py
src/api/store/graph.py

I added an endpoint that calculates the completed actions, by category, for all the members of a given team, which will be called on the new single team page.

Add team actions endpoint

---

src/website/templates/user_registration_email.html

Issue #213 on front-end portal: email confirmation message changed to what was given in the ticket

changed user registration email to Kaat's text

---

src/_main_/settings.py
src/api/handlers/graph.py
src/api/services/testimonial.py
src/api/store/graph.py
src/api/store/team.py
src/api/store/testimonial.py
src/database/models.py

Carbon Impact Query Speed-up

---

src/api/tests/test_graphs.py
src/api/tests/test_teams.py

Just test routines - these will provide examples for further testing of alll the routes

Merge josh-testing into development

---

src/api/store/download.py
src/api/store/graph.py
src/api/store/team.py

Teams routes changes

---

src/api/handlers/action.py
src/api/handlers/community.py
src/api/handlers/goal.py
src/api/handlers/graph.py
src/api/handlers/message.py
src/api/urls.py
src/authentication/middleware.py

Tried to test from development, found these errors which you may already have fixed
With these build errors fixed, testing locally I get the error "session_expired" on the initial communities.list

Fix some build errors and clean ups

---

src/_main_/settings.py
src/_main_/urls.py
src/_main_/utils/context/__init__.py
src/api/decorators.py
src/api/handlers/auth.py
src/api/handlers/team.py
src/api/handlers/testimonial.py
src/api/handlers/userprofile.py
src/api/services/auth.py
src/api/store/community.py
src/api/store/subscriber.py
src/carbon_calculator/calcUsers.py
src/carbon_calculator/views.py

Making Adjustments to the API so that the admin site can also benefit from the cookies etc

Fixing api for admin and portal

---

src/_main_/config/build/deployNotes.txt
src/api/handlers/testimonial.py
src/api/handlers/userprofile.py

Fix a misspelling that broke testimonials

Testimonial bug fix

---

src/_main_/utils/common.py
src/api/handlers/subscriber.py
src/api/handlers/team.py
src/api/services/team.py
src/api/store/team.py
src/api/store/testimonial.py

Fixes to team creation and updating and subscribe to newsletter

Address community portal issue 318 and 244

---

src/api/handlers/testimonial.py
src/api/store/team.py

Fixes issue portal issue 361 where communty id passed as a string like "82"

Allow IDs passed to testimonials.add to be int strings

---

src/api/handlers/subscriber.py
src/api/store/download.py
src/api/store/subscriber.py
src/carbon_calculator/content/exportdefaults.csv
src/carbon_calculator/tests/tests.py

Portal issue 306
Also add some carbon calculator unit tests Tori (HS intern) created

Fix subscriber bug

---

src/api/handlers/team.py
src/api/store/team.py
src/website/templates/new_admin_email.html

Fix 2 teams related bugs

---

src/api/handlers/graph.py
src/api/handlers/subscriber.py
src/api/store/page_settings__home.py
src/api/store/team.py

Also a subscriber bug fix and small clean up

Issue 240 

---

src/_main_/settings.py
src/api/handlers/download.py
src/api/store/community.py
src/api/store/download.py
src/api/store/team.py

Fixes two broken features:
All communities download
Create Community

Fix admin issues 218 and 253

---

.gitignore
src/_main_/settings.py
src/api/handlers/team.py
src/api/store/team.py

Related to front end ticket 445. Removing team photos on update

Pongo backend development

---

src/_main_/urls.py
src/api/handlers/auth.py
src/api/handlers/team.py
src/api/store/team.py
src/authentication/middleware.py
src/database/models.py

Keep admin sessions alive
Send User join date

Keep admin sessions alive and 

---

src/authentication/middleware.py
src/database/models.py

Avoid automatic sign-out after 1 hour

Don't check expiry date on firebase key

---

src/api/handlers/event.py
src/api/handlers/page_settings.py
src/api/handlers/testimonial.py
src/api/services/event.py
src/api/services/testimonial.py
src/api/store/event.py
src/api/store/testimonial.py
src/api/tests/test_events.py
src/api/tests/test_testimonials.py
src/database/models.py

Also include Owen's test routines and bug fixes

Make goals consistent, in one place

---

src/_main_/settings.py
src/_main_/utils/validator/__init__.py
src/api/handlers/team.py
src/api/store/community.py
src/api/store/team.py

Frontend-portal issue 561

---

src/api/handlers/vendor.py
src/api/store/vendor.py

Several bugs in the vendor create and update (from Owen's work)

API 274 - Vendor create and update

---

src/api/services/page_settings.py
src/api/store/action.py
src/api/store/event.py
src/api/store/userprofile.py

Copied Events or Actions do not get labeled as Templates
Accidently committed part of this to Development directly.  My bad.

Merge two fixes into Dev

---

src/api/store/page_settings.py

Model supports multiple images, though code currently supports single.
No model changes required.

Fix pageSetting images

---

src/website/templates/base.html
src/website/templates/community.html
src/website/templates/page__about_us.html
src/website/templates/page__contact_us.html
src/website/templates/page__donate.html
src/website/templates/page__impact.html
src/website/templates/sitemap_template.xml
src/website/urls.py
src/website/views.py

Add aboutus, donate, contactus, impact to SEO Pages

Add aboutus, donate, contactus, impact to SEO Pages

---

src/api/store/userprofile.py
src/database/apps.py

Fxnality to remove profile picture when user tries to delete.

Pongo profile pic mods

---

src/_main_/urls.py
src/api/store/community.py

#320 320 communities.listForCommuityAdmin returns all for a super admin (even if also a cadmin);
#321 Fix error from reserve_subdomain
#322 Create action - carbon calc box empty

Issues 320, 321, 322

---

src/api/store/event.py
src/api/store/vendor.py
src/api/tests/test_events.py

Issue #287 - recurring events
Issue #331 - error from events.date.update
Also fix bug in Vendor patch #329

Fixes for recurring events on API

---

src/api/handlers/community.py
src/api/services/community.py
src/api/store/community.py
src/api/store/event.py
src/api/store/userprofile.py
src/api/tests/test_events.py
src/database/models.py

Issue 287 - improve the recurring event functionality by passing in final_date separately.
Issue 334 - specify custom website as part of community creation and updating

Issues 287 (improved) and 334

---

src/api/handlers/userprofile.py
src/api/services/userprofile.py
src/api/store/userprofile.py
src/website/templates/community_invitation_email.html
src/website/templates/team_invitation_email.html

Created two html mail templates, one for invitation to a team, one for invitation to a community.

Fix user invitation e-mails

---

src/api/store/download.py
src/api/store/userprofile.py

Downloads and removing actions from done

Issues 366,367, 368

---

src/Makefile
src/_main_/settings.py
src/api/handlers/auth.py
src/api/handlers/download.py
src/api/services/admin.py
src/api/services/download.py
src/api/store/download.py
src/api/tests/test_carbon_equivalencies.py
src/api/tests/test_download.py
src/authentication/middleware.py
src/deployment/prepare_to_deploy.py
src/website/templates/communities.html
src/website/views.py

Fix team users download and add some unit tests

---

src/Makefile
src/api/handlers/userprofile.py
src/api/services/userprofile.py
src/api/store/userprofile.py
src/api/tests/common.py
src/api/tests/test_download.py
src/api/tests/test_userprofile.py

378 - users.checkImported functionality
377 - email address checking regex

Two bug fixes relating to importing users

---

src/_main_/settings.py
src/_main_/utils/emailer/send_email.py
src/api/handlers/userprofile.py
src/api/services/userprofile.py
src/api/store/message.py
src/api/store/userprofile.py

Two issues relating to importing users
One issue so super admins see all messages

Issues 381, 382, 383

---

src/api/handlers/testimonial.py
src/api/services/testimonial.py
src/api/store/testimonial.py

I made a new branch and cleaned up the code. Hopefully now it is more easily understandable. Please note, this merge also includes Brads changes too from branch BHN-testimonial-List

backend changes for issue 400 (front end)

---

src/api/handlers/event.py
src/api/services/event.py
src/api/store/event.py
src/api/tests/test_download.py
src/api/tests/test_events.py
src/database/models.py

Events: a bugfix and route to get all RSVP responses

---

src/api/store/testimonial.py

Some back end changes for the image viewing to work correctly when updating a draft testimonial. See Image viewer commit for more details
https://github.com/massenergize/frontend-portal/commit/6cb6677daee8f62fa537b39e9282c6ea06724f28

Addition back end Changes front issue 400

---

src/_main_/utils/common.py
src/api/handlers/event.py
src/api/services/event.py
src/api/store/event.py
src/api/store/userprofile.py
src/api/store/utils.py
src/api/tests/test_download.py
src/api/tests/test_events.py
src/database/models.py

Issues fixed to avoid bad JSON error on RSVP requests.  A new route to return RSVP lists for CADMINs to view in admin portal.  No Model changes

Event RSVP Fixes for Prod

---

src/api/handlers/action.py
src/api/handlers/team.py
src/api/handlers/vendor.py
src/api/services/action.py
src/api/services/vendor.py
src/api/store/action.py
src/api/store/event.py
src/api/store/team.py
src/api/store/vendor.py
src/api/tests/test_events.py
src/database/models.py

Issue #409 
Back end support to support copying content from other communities (Admin #420)

Allow Cadmins to retrieve all communities lists (actions, events, teams, vendors)

---

src/_main_/utils/common.py
src/api/handlers/event.py
src/api/handlers/userprofile.py
src/api/store/userprofile.py
src/database/models.py

A few fixes relating to dates and UserActionRels

417 Minor fixes for action dates

---

src/api/handlers/event.py
src/api/handlers/message.py
src/api/handlers/team.py
src/api/handlers/testimonial.py
src/api/services/message.py
src/api/services/testimonial.py
src/api/services/userprofile.py
src/api/store/event.py
src/api/store/message.py
src/api/store/team.py
src/api/store/testimonial.py
src/api/tests/test_testimonials.py
src/database/models.py
src/website/templates/testimonial_submitted_email.html

395 - Forwarded messages to team admin, savve the edited version
420 - Notify primary cadmin when a testimonial is submitted
421 - unable to change TeamMember status in admin portal
Enable/Disable event RSVPs

Four API issues fixed

---

src/api/handlers/page_settings.py
src/api/handlers/team.py
src/api/handlers/userprofile.py
src/api/store/community.py
src/api/store/page_settings.py

Issue 423 - consistency of data and preferences for community admin data selection

Fixes for data issues

---

src/api/store/testimonial.py

Simple fix for updating testimonials

430- update testimonial error

---

src/api/services/userprofile.py
src/api/store/page_settings.py
src/api/store/userprofile.py
src/database/raw_data/portal/menu.json
src/website/templates/testimonial_submitted_email.html

Adding users and impact page settings

Two bug fixes

---

src/_main_/settings.py
src/_main_/utils/common.py
src/_main_/utils/context/__init__.py
src/api/handlers/misc.py
src/api/services/misc.py
src/api/store/misc.py
src/api/tests/common.py
src/authentication/middleware.py

Routes and tiny changes to help tests. Everything else should be normal

Pongo backend token route for fe testing

---

.github/workflows/tests-dev.yml
src/.gitignore
src/Makefile
src/_main_/settings.py
src/_main_/utils/emailer/send_email.py
src/_main_/utils/utils.py
src/api/services/utils.py
src/api/store/download.py
src/api/store/graph.py
src/api/tests/common.py
src/carbon_calculator/CCDefaults.py

The goal of this PR is to make the github action that runs tests be configured well enough to run the tests we have.
If we dont fix this, with our rapid development, we could commit some bugs without realizing.
Also some of our tests were creating files and storing them in our s3 bucket each time we run our tests 😂  so i fixed that. Whew 😌 !
Strategy:
I introduce a new run mode called `test`.  When the api is running in test mode, it will create and use a sqlite file as the db instead of trying to connect to a remote host.
Its faster this way and allows the github action to run tests for us without having to provide a remote db access.

Fix tests for github action

---

src/api/handlers/auth.py
src/api/services/auth.py
src/api/services/userprofile.py
src/api/store/userprofile.py

New route auth.sigininasguest
SImple changes to users.create

473 - back end changes for guest user sign-in

---

src/api/handlers/userprofile.py
src/api/store/userprofile.py
src/api/utils/constants.py
src/database/models.py

Don't automatically turn a standard user instead of a guest user

Updates to users.create

---

src/website/templates/communities.html

Found that our landing page looked a bit off on mobile. So I just cleared it up a bit 
Was like this: 
Now its like this:

responsive landing page

---

src/_main_/utils/emailer/send_email.py

Removed print statements

---

src/database/models.py

Works with this admin portal PR : https://github.com/massenergize/frontend-admin/pull/614

tweaked team admin info on model

---

src/database/models.py

Make the feature flags work for EVERYONE, ALL_EXCEPT and SPECIFIED communities and users.

567 - Fix FeatureFlag logic

---

src/requirements.txt

Revert "Bump pyjwt from 1.7.1 to 2.4.0 in /src"

---

src/api/store/event.py

This PR contains code that validates start and end date and time of event during creation and edit. Related [issue](https://github.com/massenergize/frontend-admin/issues/716)

Events creation and edit bug fix

---

src/_main_/utils/footage/spy.py
src/api/store/community.py
src/api/store/event.py
src/api/store/vendor.py

Sorted out what was making the tests fail

sorted out what was making the tests fail

---

src/database/utils/settings/admin_settings.py

Related ticket https://github.com/massenergize/frontend-admin/issues/749

modified preference options

---

src/api/handlers/download.py
src/api/handlers/misc.py
src/api/services/download.py
src/database/utils/settings/admin_settings.py
src/database/utils/settings/user_settings.py

This is work in progress, so labeled as "Draft".   I would like this to be in the upcoming release if possible.
Addressing Admin issue #773 ([Communication Preferences for cadmins](https://github.com/massenergize/frontend-admin/issues/773))

Changes for communication preferences and nudge request

---

src/task_queue/events_nudge/__init__.py

Fix the cadmin nudge which didn't go out to anyone.

624 - Nudge should go weekly if admins haven't set comm prefs

---

src/api/handlers/event.py
src/api/store/event.py

Matching API changes for unsharing events

allow even unsharing

---

src/api/store/tag_collection.py

fixed tag collections delete endpoint returning undefined response to the frontend

Tag collection delete endpoint returning undefined response

---

src/api/handlers/team.py
src/api/services/action.py
src/api/services/admin.py
src/api/services/event.py
src/api/services/team.py
src/api/services/testimonial.py
src/api/services/vendor.py
src/api/store/graph.py
src/api/store/team.py
src/api/store/userprofile.py

Fix two API tickets:
#634 Only super admin alerts for canary or prod
#636 Fix team photo upload from user portal

Super admin alerts & fix for team photo upload

---

src/_main_/settings.py
src/api/handlers/community.py
src/api/services/summary.py
src/api/store/common.py
src/api/store/community.py
src/api/store/summary.py

More Changes For User Engagements (For Admins)

---

src/database/utils/settings/user_settings.py

Related [Issue](https://github.com/massenergize/frontend-portal/issues/1142) 
User Portal [PR](https://github.com/massenergize/frontend-portal/pull/1163)

user communication prefs

---

src/api/handlers/team.py
src/api/store/community.py
src/api/store/team.py
src/api/store/vendor.py

API bug fixing from testing

---

src/api/store/summary.py

email instead of id

---

src/website/views.py

647 - fix error from vendors.listForCommunityAdmkn
652 - sort communities alphabetically on community list regardless of capitalization

API Bug fixes: Issues 647 and 652

---

src/api/handlers/page_settings.py
src/api/store/page_settings.py

page settings update now u ses mlibrary image selection structure

---

src/api/services/webhook.py

added a null check for the postmark test and also fixed string split in get_message id function

Inbound message postmark

---

src/_main_/utils/footage/FootageConstants.py
src/_main_/utils/footage/spy.py
src/api/store/userprofile.py

now records mou footage

---

src/api/store/page_settings__home.py

Reset error

---

src/api/store/download.py

Addresses changes in ticket #702 to the metrics csv report.

all metrics download fixes

---

src/api/store/community.py
src/api/store/userprofile.py
src/api/utils/constants.py
src/task_queue/views.py

1. Fix the communities.listForCommunityAdmin (or super admin) to properly order the list;
2. Fix the ME_SUPPORT_TEAM_EMAIL
3. Fix and diagnostic print for the MOU notificaiton nudge

Three fixes

---

src/api/handlers/userprofile.py
src/api/store/userprofile.py

Updated the users list route for super admins to allow  fetching users belonging to a list of communities
Works with [Admin Portal PR](https://github.com/massenergize/frontend-admin/pull/984)

Loading Data for Form Fields

---

src/api/store/team.py

We can now get Teams for admins belonging to a specific community

Team Parent During Creation

---

src/database/models.py

added more mou details to user obj

---

src/api/store/action.py
src/api/store/testimonial.py
src/api/store/vendor.py
src/api/tests/test_actions.py
src/api/tests/test_mou_reminder.py
src/task_queue/views.py

Update unit test for the sending MOU notification, where there were failures
Also fix bugs in actions.update, vendors.update and testimonials.update caught by test failures

Fix tests and 3 update bugs

---

src/api/handlers/auth.py
src/socket_notifications/consumers/user_session_tracker_consumer.py

Extend admin session time

---

src/_main_/settings.py
src/database/models.py

Action users Improvement

---

src/api/services/summary.py
src/api/store/summary.py

Testimonials count Fixed

---

src/api/handlers/community.py
src/api/store/community.py

Crash in dev was due to some bad data in the database, a location without a zipcode.  Added protection

Fix Zipcode error

---

src/_main_/asgi.py
src/_main_/settings.py
src/_main_/wsgi.py
src/socket_notifications/routing.py

This PR removes all traces of the channels that was causing all api endpoints to fail.

Dev platform Fix

---

src/api/handlers/community.py
src/api/store/community.py
src/api/store/download.py
src/task_queue/events_nudge/user_event_nudge.py

Simple bug fixes to get merged before prod deployment

Issues 758, 759 fixed

---

src/_main_/settings.py

Simplify Sentry initialization - same in all repositories

767 - tweak to Sentry initialization

---

src/database/models.py

Move calculation of community impact for consistency on App and Website.

769 - move community impact calculations to API

---

src/task_queue/events_nudge/cadmin_events_nudge.py
src/task_queue/events_nudge/user_event_nudge.py

User Event Nudge Users List Fix

---

src/database/models.py

added null check to prevent breaking of website

---

src/task_queue/events_nudge/user_event_nudge.py

This change fixes 3 issues which prevents the user event nudge from going out.

776 - user events nudge bug fixes

---

src/_main_/utils/common.py
src/api/services/auth.py
src/task_queue/events_nudge/cadmin_events_nudge.py
src/task_queue/events_nudge/user_event_nudge.py

-  Portal [PR](https://github.com/massenergize/frontend-portal/pull/1265)
- Admin [PR](https://github.com/massenergize/frontend-admin/pull/1092)

Fix: Event Nudge Pref Link 

---

src/_main_/utils/common.py
src/api/services/userprofile.py
src/api/store/download.py
src/api/store/event.py
src/carbon_calculator/content/all-actions-update.csv
src/database/models.py
src/task_queue/database_tasks/update_actions_content.py

From canary testing, several bugs have been fixed.
#821 
#822 
#823 
#824 
#825 
please refer to the individual issues for details
* [x ] I've tested my changes manually.

Bug fixes from testing - issues 821, 822, 823, 824, 825

---

src/api/services/admin.py
src/carbon_calculator/content/all-actions-update.csv

A bug fix to address issue #828 
Also improve all-actions-update.csv to clean up database actions

Bug fix - add_admin fails

---

src/task_queue/nudges/user_event_nudge.py

Fix two minor issues with the user events nudge

832 - User events nudge issues

---

src/task_queue/nudges/user_event_nudge.py

now sorting by start_date

---

src/task_queue/nudges/user_event_nudge.py

Minor changes for automated nudge emails to sort events by date and use 12 hour time

Prod update to fix User Events Nudge

---

src/api/store/campaign.py
src/apps__campaigns/helpers.py
src/website/templates/campaign.html
src/website/templates/campaign_technology.html
src/website/urls.py
src/website/views.py

- Made a few edits. Created two new html routes for campaign, and a technology for SEO. 
- Also edited home route in the navigation generation step for the campaign navbar

Campaign unfurling

---

src/api/handlers/campaign.py
src/api/store/campaign.py
src/api/store/download.py
src/apps__campaigns/models.py

This pull request fixes issues in the campaign handler validator and store. It adds a missing "role" field in the validator and updates the store to return the correct objects.

Fix campaign handler validator and store issues

---

src/_main_/settings.py
src/api/handlers/campaign.py
src/api/services/campaign.py
src/api/store/campaign.py
src/apps__campaigns/helpers.py
src/apps__campaigns/models.py

This pull request adds an API endpoint for updating the key contact of a campaign. It includes the necessary changes to the backend code and database models.

Add campaign key contact update API endpoint

---

src/api/store/campaign.py
src/api/store/vendor.py

The commit refines the campaign and vendor query filters. Campaign comments and testimonials now also check for is_deleted status on the associated campaign_technology. In vendor retrieval, items created via campaign are now excluded. These changes assure more accurate and relevant returns from queries.

Update campaign comments, testimonials, and vendor filters

---

src/api/store/message.py
src/api/store/vendor.py
src/api/tests/test_media_library.py
src/api/tests/test_message.py
src/api/tests/test_userprofile.py
src/database/models.py

This pull request addresses various issues with the existing tests:
-  UserProfile tests were failing due to issues related to the request content-type.
- Vendor tests were broken as SQLite does not support a specific database lookup.
-  MediaLib tests dependent on S3 bucket access have been temporarily commented out since the required setup is not available in the test environment at the moment.

Fixed Failing Tests In Dev

---

src/apps__campaigns/helpers.py
src/apps__campaigns/models.py

closes https://github.com/massenergize/massenergize-campaigns/issues/159

Added Technologies to the Menu  Items

---

src/api/services/campaign.py
src/api/store/campaign.py

Feat: minify the returned object for events and testimnials when importing for campaign

---

src/_main_/settings.py
src/task_queue/tasks.py

This pull request introduces several enhancements and a new feature to our project. The key changes in this PR include:
- Refactor server and Celery running conditions: The conditions to check whether the server and Celery are running in the local environment have been simplified. Now, it just checks against the IS_LOCAL flag which makes our code cleaner and more manageable.
- Slack Notifications: A new feature has been added which sends notifications to a designated Slack channel whenever a task is run, based on its status (scheduled, succeeded, or failed). This feature is intended to help us monitor task execution in a production environment in real-time, and should aid in rapid response to issues and errors.

feat: Add Slack Notifications, Refactor Server and Celery Running Conditions

---

src/api/store/common.py
src/api/store/event.py

fix: Null has no update when updating event info

---

src/api/store/event.py

Simplified the data fetching code in event.py by refactoring the database query for events. Further, implemented enhanced access control for creating event reminder settings. Now, admin types are differentiated and only super admins can create settings for all communities, whereas community admins can only create settings for communities they administer. Also, optimized and tidied up the code by removing redundant whitespaces and reorganizing clauses.

Refactor event data fetching and access control

---

src/api/store/event.py
src/api/store/testimonial.py
src/database/models.py

This pull request includes changes to improve the retrieval of image data in the models.py file. The get_json_if_not_none function has been replaced with the get_summary_info function for more efficient and comprehensive data management. Additionally, model methods and database queries have been refactored for clarity and simplicity. The simple_json method has been replaced with the info method in the database models file, and unnecessary variables and operations have been removed.

Refactor: Optimize queries for Events and Testimonials

---

src/database/models.py

Communities list route enhanced

---

src/api/store/community.py

This pull request simplifies and refactors the retrieval of community feature flags to improve database query efficiency. It also adds a condition check before calling 'bulk_create' on 'CommunityNotificationSetting' to avoid creating empty records.

Refactor community feature flags retrieval and creation

---

src/api/handlers/community.py
src/api/services/community.py
src/api/store/campaign.py
src/api/store/community.py
src/database/models.py

This pull request introduces the following changes:
These changes are expected to decrease the loading time for all endpoints related to communities.

Feat: ✨  Add Community-Specific Feature Flag Fetching Endpoint

---

src/apps__campaigns/helpers.py

This Pull Request (PR) introduces an update to the way our campaign technology events are ordered. As per the changes outlined in the latest commit, campaign technology events will now be presented in a sorted, chronological order.
The key changes implemented in this update are:
Campaign Technology Events Ordering: Events are now fetched from the database in an arranged manner, sorted by their "event__start_date_and_time". This change improves readability and provides a more logical and streamlined view of the events.

Sorting Update for Campaign Technology Events

---

src/api/store/community.py

This Pull Request fixes the date conflicts on the activate_on field of platform features management model.

Fix Platform features date format

---

src/api/utils/api_utils.py

This Pull request fixes the inconsistency in the link structure for menu items.

Fix inconsistent link structure in frontend portal menu items

---

src/_main_/utils/feature_flag_keys.py
src/api/handlers/action.py
src/api/handlers/event.py
src/api/handlers/media_library.py
src/api/handlers/team.py
src/api/handlers/testimonial.py
src/api/handlers/vendor.py
src/api/store/community.py
src/api/store/event.py
src/task_queue/database_tasks/contents_spacing_correction.py
src/task_queue/nudges/postmark_sender_signature.py

This PR addresses 3 issues:
#986 - remove two feature flags no longer needed
#990 - Community Admin - add to community when they are added as admins, and dont' let them leave
#991 - eliminate duplicate events in event list.
Check that community admins are added to the community whenb they are assigned as admins.
Also check that they can't leave the community they are admins of.

Address issues 986, 990, 991

---

README.md
src/README.md

This PR just contains edits/additions to the Readme.md files

AddReadmeOnLocal

---

README.md
src/README.md

This PR adds a Readme to the api repo so that contributors have some guidance on how to run the API
N/A
N/A

Add readme

---

src/_main_/utils/emailer/send_email.py
src/_main_/utils/feature_flags/FeatureFlagConstants.py
src/api/constants.py
src/api/handlers/media_library.py
src/api/store/common.py
src/api/store/media_library.py
src/database/models.py
src/database/utils/common.py
src/task_queue/database_tasks/media_library_cleanup.py

After several manual tests, I think this  is ready to be tested. 
The actual deletion process here is muted. I have commented out that part of the code, so right now, we are only simulating deletion. All we need to do is uncomment the code when we are ready. 
[Link to Tech Spec](https://docs.google.com/document/d/1K90ERN1nO2nr84I6k7YBXGUuoCoMmML5Sg_x6BeF1xE/edit?usp=sharing) for some context
[How to test](https://docs.google.com/document/d/10PhaEVF8JCtguOUQkBqj3Tjpoa3GdwUZjTHGDGKSWC4/edit?usp=sharing)
[Here is what a final report looks like](https://drive.google.com/file/d/1kHVT9sC6be3kK2uHln8EuMWznMOyVs5q/view?usp=drive_link)

Revive image duplicates report & removal

---

.gitignore
src/api/store/download.py

This Pull request fixes the bug preventing users csv download

fix:Users csv download

---

.gitignore
src/api/handlers/webhook.py
src/api/services/webhook.py

The pull request includes enhancements and bug fixes primarily centered on refining the webhook services. The changes are as follows:
- Added a try-except block to handle JSON Decode Error during argument extraction from the request body in the bounce_email_webhook and process_inbound_webhook methods of WebhookHandler. This enhancement will log the error and provide a better response in case of invalid JSON input.
- Enhanced the error handling in webhook processing by inserting logging statements. This will assist us in diagnosing issues by recording errors in the logs. This applies to both inbound and bounce email webhooks, logging both specific and general exceptions

Fix: Add error handling in webhook processing

---

src/api/store/community.py

This pull request addresses and fixes an issue related to saving custom website URLs.

Fix: Save Custom Website URL Issue

---

src/carbon_calculator/carbonCalculator.py
src/carbon_calculator/models.py
src/database/models.py

Related to : https://github.com/massenergize/frontend-admin/issues/1119
Works with F.E PR: https://github.com/massenergize/frontend-admin/pull/1202

Feat: Carbon Calculator Categories & SubCategories Response Object Modifications

---

src/Makefile

Brought back the release command and other commands lost as a result of resolving merge conflicts.

refactor: Updated Makefile

---

src/api/handlers/misc.py
src/api/store/misc.py
src/api/tests/integration/test_custom_menu.py

Add tests for reset custom menu with multiple scenarios such as invalid payload, invalid id, normal user, super admin, and community admin. Also, added tests for list of admins function, internal link for nav and footer menu, and additional edge cases.

Test: Add multiple test cases for custom menu operations

---

src/api/services/webhook.py

In this PR, logging is added to the inbound message processing code to trace cause of failure

chore: Add logs for inbound messging bug trace

---

src/api/services/webhook.py

This Pull Request introduces a solution to the issue of inconsistent inbound message email bodies. The changes implemented in this PR focus on standardizing the email body content by trimming it down to plain text before the extraction process begins. This ensures a consistent format for all inbound message email bodies, improving the reliability and accuracy of item extraction. After merging this PR, the handling of inbound message email bodies will be more robust and consistent.

Fix: Inconsistent Inbound Message Email Bod

---

src/api/services/webhook.py
src/api/tests/unit/utils/constants.py
src/api/tests/unit/utils/test_webhooks_utils_extract_msg_id.py
src/api/tests/unit/utils/test_webhooks_utils_extract_subject_email.py

This PR adds a fix for the email extraction code for inbound processing to handle instances when the From in the message body includes mailto. Tests have been added for the utility functions.

Fix: Email extraction with mailto

---

src/_main_/utils/base_model.py
src/database/models.py

This pull request includes changes made to the models in the `database.models.py` file. Specifically, the attribute 'fields_to_translate' has been added to multiple classes to provide better i18n support.

Refactor: Add fields_to_translate Attribute to Models Using CustomMeta in Database App

---

src/Makefile
src/_main_/utils/translation/__init__.py
src/_main_/utils/translation/google_translate.py
src/api/tests/unit/utils/test_translation.py

Adding JsonTranslator and utility functions to flatten and unflatten a dict without losing info
- JsonTranslator: Added a utility class for JSON translation operations.
- Flatten and Unflatten Functions: Implemented functions for flattening and unflattening nested dictionaries.
- Stubbed Translate Function: Included a placeholder function for future integration with Google Translate API.
`DJANGO_ENV=test python3 -m coverage run --source='.' manage.py test api.tests.unit.utils.test_translation.TestJsonTranslator`

add JsonTranslator and unit tests

---

src/api/handlers/translation.py
src/api/services/translation.py
src/api/store/translation.py
src/api/tests/integration/test_tranlations_integration.py
src/api/urls.py
src/database/raw_data/other/languages.json

This pull request introduces the following changes:
- Introduced a new `languages.json` file in the `src/database/raw_data/other` directory, containing various foreign language options along with their respective country codes.
- An endpoint for fetching all languages that a super admin can add as supported languages for translation on the platform.

feat: Implemented an endpoint for retrieving all languages

---

src/api/handlers/misc.py
src/api/templates/rewiring_america.html
src/database/raw_data/portal/menu.json
src/website/urls.py

This PR moves the Rewiring America code from the website Django app to the api app so that the community portal can load it from the api.massenergize.* endpoint.

Refactor: Brought back rewiring America menu item 

---

src/Makefile
src/api/tests/unit/utils/test_filter_functions.py
src/api/utils/filter_functions.py

This commit corrects the logic used to sort items based upon provided parameters, changing default sorting direction from "desc" to "asc". Additionally, exception handling has been added in the sorting function to ensure graceful failure and return the original query set in the event of an error.

fix: Sorting logic for listing data

---

src/api/handlers/misc.py
src/api/services/misc.py
src/api/store/misc.py
src/api/tests/integration/test_tranlations_integration.py
src/database/raw_data/other/languages.json

This pull request introduces a new endpoint to fetch all languages and includes corresponding integration tests to ensure the functionality works as expected.

Feat:  add all languages endpoint and test

---

src/_main_/settings.py
src/_main_/utils/stage/__init__.py
src/_main_/utils/stage/gtranslate_helper.py
src/_main_/utils/translation/translator/__init__.py
src/_main_/utils/translation/translator/providers/google_translate.py
src/api/tests/unit/utils/test_filter_functions.py

Currently the tests are broken for translator util branch where we introduce google translate and microsoft translate and a lot of the other nifty utils.
This pr fixes that
Created a mock Client for testing purposes so we actually dont end up calling google translate itself.  for now, its a no-op and returns the same text.

fix tests for translator util changes

---

src/_main_/utils/common.py
src/_main_/utils/validator/__init__.py
src/api/handlers/graph.py
src/api/handlers/page_settings__home.py
src/api/handlers/subscriber.py
src/api/handlers/testimonial.py
src/api/store/misc.py
src/api/tests/integration/test_custom_menu.py

The most recent production release `v6.2.2` introduced a number of bugs. This pull request addresses the following

fix: footer  items and validation

---

src/_main_/utils/context/__init__.py
src/apps__campaigns/models.py
src/database/models.py

In this Pull Request, I have made the following key changes:
- The `__preferred_language` key has been updated to` __user_language` in the `context/init.py` file.

refactor: update language key

---

src/api/middlewares/translation_exclusion_patterns.py
src/api/middlewares/translation_middleware.py

This PR fixes the custom translation filters in the endpoint, ensuring accurate and consistent filtering of translations.

Fix: custom translation filter

---

src/_main_/utils/translation/__init__.py
src/api/middlewares/translation_exclusion_patterns.py
src/api/middlewares/translation_middleware.py

This PR fixes the custom translation filters in the endpoint, ensuring accurate and consistent filtering of translations.

Fix: Translation filter by endpoint

---

src/_main_/utils/emailer/send_email.py
src/api/services/utils.py

This pull request adds background execution for email and Slack notifications for better performance, and enhanced logging for email errors.
https://github.com/user-attachments/assets/59cb844c-9513-4bab-87d1-d8dc369432ef

✨ feat: add background execution for emails and Slack notifications

---

src/_main_/utils/translation/__init__.py
src/api/middlewares/translation_exclusion_patterns.py
src/api/middlewares/translation_middleware.py

This pull request Updated the translation exclusion patterns which includes further exclusion patterns for `/campaigns.technologies.info`, addition of new global exclusion key patterns and enhanced key exclusion logic in `JsonTranslator`. These changes significantly elevate translation handling and customization.

Refactor: Enhancements in Translation Exclusion Patterns

---

src/_main_/utils/common.py
src/_main_/utils/translation/__init__.py
src/_main_/utils/translation/translator/__init__.py
src/_main_/utils/utils.py
src/api/tests/unit/utils/test_calc_string_list_length.py

This pull request Introduced functions for logging metrics to Sentry and integrated them into the translation process. This enhances monitoring and reporting of translation activities and performance.

Translation metrics

---

src/api/middlewares/translation_exclusion_patterns.py

This PR updates the regex filter to exclude vendor names from being translated.

Fix: Vendors section title and description translation.

---

src/api/handlers/technology.py

This pull request adds `overview_title` as an optional field to the `technologies.update` route, allowing the field to be updated.

feat(api): add optional field for overview title

---

src/_main_/utils/common.py
src/_main_/utils/context/__init__.py
src/_main_/utils/translation/__init__.py
src/_main_/utils/translation/metrics_tracker.py
src/_main_/utils/translation/translator/__init__.py
src/api/middlewares/translation_middleware.py
src/api/store/campaign.py
src/database/utils/common.py

This pull request includes the following changes:
- **Translation Metric**:
- Implemented `TranslationMetrics` to track language usage, latency, and error rates.
- **Fix Database Handlings**: Handle the missing `info` method gracefully to prevent errors.
- **Refactor Utility Functions**: Removed deprecated and unused Sentry logging functions for cleaner codebase.
- **Campaign View Fix**: Enhanced the CampaignView transaction logic to prevent race conditions by ensuring it is properly retrieved or created.

Feat/translation Metrics

---

src/_main_/utils/translation/metrics_tracker.py

This pull request separates Cloud Watch metrics logs for development (dev), canary, and production (Prod) environments

Update metrics_tracker.py to include environment namespace

---

src/api/handlers/misc.py
src/api/store/misc.py

This pull request includes changes to the `src/api/handlers/misc.py` and `src/api/store/misc.py` files to update the handling of community IDs in the internal links functionality. The most important changes are:
Updates to handling of community IDs:
* [`src/api/handlers/misc.py`](diffhunk://#diff-577b3d06af5e0c9d6f2e0366129c8ec2e8fd48421b285a031f87c00b14a16c12L359-R359): Changed the validator to expect a list of community IDs (`community_ids`) instead of a single community ID (`community_id`).
* [`src/api/store/misc.py`](diffhunk://#diff-9e40a4f642237224df0cd7a4ebd880f5cecbcaa00a07794ccd93d0938642e6d5L700-R700): Updated the retrieval of community IDs to handle a list (`community_ids`) instead of a single ID (`community_id`).

Fix: internal links lists

---

src/_main_/settings.py
src/_main_/utils/massenergize_logger/__init__.py
src/api/middlewares/url_resolver_middleware.py
src/api/tests/integration/test_communities.py
src/website/views.py

This pull request includes several changes to improve middleware functionality, logging, and URL handling in the codebase. The most important changes include adding a new URL resolver middleware, enhancing the logging mechanism to handle empty messages, and updating a utility function to return an empty string instead of `None`.
Middleware improvements:
* [`src/_main_/settings.py`](diffhunk://#diff-b165c472c9cd1c156ddaf1519b16e41750d8b17e0a509a57a70042a7b57e7024R105): Added `URLResolverMiddleware` to the middleware list.
* [`src/api/middlewares/url_resolver_middleware.py`](diffhunk://#diff-a0de160993d2332f76e0fe4111944be66ab8510c2c945ec8bb6d7a92232d742aR1-R15): Implemented `URLResolverMiddleware` to handle 404 errors for unresolved URLs.
Logging enhancements:
* …

Add URLResolverMiddleware and improve logging in MassenergizeLogger

---

.github/workflows/tests-dev.yml
src/api/tests/common.py
src/task_queue/nudges/cadmin_testimonial_nudge.py

- Added a new `format_date` function to handle date formatting with a fallback
- Enhanced error handling in `get_admin_testimonials` with try-except block and logging
- Added detailed logging in `prepare_testimonials_for_community_admins` to track nudge processing
- Improved error logging for cases where no testimonials are found or nudge sending fails

Refactor: Improve Testimonial Nudge Error Handling and Logging

---

src/api/store/download.py
src/api/tasks.py

Fix typo on actions-users download

FIx for #1206 - actions-users download
